---
all:
  children:
    # The DNS group
    dns:
      hosts:
        10.0.0.30:
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/vagrant/.ssh/machines_keys/dns_private_key
    
    # The Webservers group
    webservers:
      hosts:
        10.0.0.20:
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/vagrant/.ssh/machines_keys/web_private_key
