---
all:
  children:
    # The DNS group targets the specific 192.168.56.11 IP
    dns:
      hosts:
        10.0.0.30:
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/vagrant/.ssh/machines_keys/dns_private_key
    
    # The Webservers group targets the two web nodes
    webservers:
      hosts:
        10.0.0.20:
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/vagrant/.ssh/machines_keys/web_private_key
        # 192.168.56.22:
        #   ansible_user: vagrant
        #   ansible_ssh_private_key_file: /home/vagrant/.ssh/vagrant_keys/web2_private_key