---
# vars/servers.yml
# Example servers file.
# Generate this file using => scripts/generator/locations.sh

# servers:
#   dns:
#     - bob
#   web:
#     - alice
#     - bob
#     - charlie