---

# ssh_public_keys:
#   # Replace the string below with your actual public key output
#   alice: "ssh-ed25519 AAAAC3Nz... vagrant@ansible"
#   bob: "ssh-ed25519 AAAAC3Nz... vagrant@ansible"
#   charlie: "ssh-ed25519 AAAAC3.. vagrant@ansible"